### ISSUE TITLE
Gibberish result

### ISSUE THREAD

**Issue by OxMarco** [Maiux92/digispark-keyboard-layout-italian#2]
Tried running the test code, gives out

> YZèù+&?<abcdefghijklmnopqr9çò;ì:_"ABCDEFGHIJKLMNOPQR)=(^,'.-01T`à !57V\|SUsu8$3/2%W

**Comment by Maiux92** [comment]
Did you place DigiKeyboard.h and scancode-ascii-table.h into the DigisparkKeyboard library, inside your Arduino15 folder?

Which keyboard layout did you setup on your computer?

**Comment by OxMarco** [comment]
Followed that procedure, keyboard layout changed to Italian when plugging the device in
