### ISSUE TITLE
special characters conversion

### ISSUE THREAD

**Issue by ghost** [Maiux92/digispark-keyboard-layout-italian#3]
I followed the instructions and replaced the files:
DigiKeyboard.h
scancode-ascii-table.h

A single character is not converted.
The character \

I have done:
#include "DigiKeyboard.h"
void setup() {
}
void loop() {
  DigiKeyboard.delay(2000);
  DigiKeyboard.sendKeyStroke(0);
  DigiKeyboard.sendKeyStroke(KEY_R, MOD_GUI_LEFT);
  DigiKeyboard.delay(600);
  DigiKeyboard.print("notepad");
  DigiKeyboard.sendKeyStroke(KEY_ENTER);
  DigiKeyboard.delay(1500);
  DigiKeyboard.print("| \ ! £ $ % & / ( ) = ? ^ ");

The output writing was: | ! $ % & / ( ) = ? ^ 

So the character \ is not recognized. It should be ASCII code 92, but I don't know where to make the necessary change.
Could you help me?
Thank you!

**Comment by Maiux92** [comment]
The \ char usually escapes the subsequent character. Try to put \\ instead of a single \. It should print one.
